---
version: '3.7'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    #environment:
    #  PORT: 3000
    #ports:
    #  - 3000:3000
    volumes:
      - ..:/workspace
    user: root
    working_dir: /workspace
    command: sleep infinity
  zabbix-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-5.0-latest
    environment:
      DB_SERVER_HOST: "zabbix-db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
    depends_on:
      - "zabbix-db"
    links:
      - "zabbix-db"
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-5.0-latest
    environment:
      DB_SERVER_HOST: "zabbix-db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
      ZBX_SERVER_HOST: "zabbix-server"
      PHP_TZ: "Etc/GMT+1"
    depends_on:
      - "zabbix-db"
      - "zabbix-server"
    links:
      - "zabbix-db"
      - "zabbix-server"
    ports:
      - "8080:8080"
